name: CI build
run-name: CI build

on:
  pull_request:
    branches:
      - main

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== DEBUG ==="
          echo "github ref: " ${{ vars.GITHUB_REF }}
          echo "github ref: " ${{ env.GITHUB_REF }}
          echo "dotnet version: " ${{ vars.DOTNET_VERSION }}
          echo "event name: " ${{ github.event_name }}
          echo "=== DEBUG END ==="
          
  feature_branch:
    name: Every time
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setting up dotnet with ${{ vars.DOTNET_VERSION }} version
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal